// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListScannedHandlerFunc turns a function with the right signature into a list scanned handler
type ListScannedHandlerFunc func(ListScannedParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListScannedHandlerFunc) Handle(params ListScannedParams) middleware.Responder {
	return fn(params)
}

// ListScannedHandler interface for that can handle valid list scanned params
type ListScannedHandler interface {
	Handle(ListScannedParams) middleware.Responder
}

// NewListScanned creates a new http.Handler for the list scanned operation
func NewListScanned(ctx *middleware.Context, handler ListScannedHandler) *ListScanned {
	return &ListScanned{Context: ctx, Handler: handler}
}

/*ListScanned swagger:route GET /listscanned listScanned

List scanned pictures

List scanned pictures

*/
type ListScanned struct {
	Context *middleware.Context
	Handler ListScannedHandler
}

func (o *ListScanned) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListScannedParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
