// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Magicking/celkopier/models"
)

// ListScannedOKCode is the HTTP code returned for type ListScannedOK
const ListScannedOKCode int = 200

/*ListScannedOK List of scanned pictures

swagger:response listScannedOK
*/
type ListScannedOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewListScannedOK creates ListScannedOK with default headers values
func NewListScannedOK() *ListScannedOK {

	return &ListScannedOK{}
}

// WithPayload adds the payload to the list scanned o k response
func (o *ListScannedOK) WithPayload(payload []string) *ListScannedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list scanned o k response
func (o *ListScannedOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListScannedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*ListScannedDefault Internal error

swagger:response listScannedDefault
*/
type ListScannedDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListScannedDefault creates ListScannedDefault with default headers values
func NewListScannedDefault(code int) *ListScannedDefault {
	if code <= 0 {
		code = 500
	}

	return &ListScannedDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list scanned default response
func (o *ListScannedDefault) WithStatusCode(code int) *ListScannedDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list scanned default response
func (o *ListScannedDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list scanned default response
func (o *ListScannedDefault) WithPayload(payload *models.Error) *ListScannedDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list scanned default response
func (o *ListScannedDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListScannedDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
