// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ScanHandlerFunc turns a function with the right signature into a scan handler
type ScanHandlerFunc func(ScanParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ScanHandlerFunc) Handle(params ScanParams) middleware.Responder {
	return fn(params)
}

// ScanHandler interface for that can handle valid scan params
type ScanHandler interface {
	Handle(ScanParams) middleware.Responder
}

// NewScan creates a new http.Handler for the scan operation
func NewScan(ctx *middleware.Context, handler ScanHandler) *Scan {
	return &Scan{Context: ctx, Handler: handler}
}

/*Scan swagger:route POST /scan scan

Start scanner

*/
type Scan struct {
	Context *middleware.Context
	Handler ScanHandler
}

func (o *Scan) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewScanParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
