// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"mime/multipart"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
)

// NewUploadParams creates a new UploadParams object
// no default values defined in spec.
func NewUploadParams() UploadParams {

	return UploadParams{}
}

// UploadParams contains all the bound params for the upload operation
// typically these are obtained from a http.Request
//
// swagger:parameters upload
type UploadParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Scanned image
	  Required: true
	  In: formData
	*/
	Scanned io.ReadCloser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUploadParams() beforehand.
func (o *UploadParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return errors.New(400, "%v", err)
		} else if err := r.ParseForm(); err != nil {
			return errors.New(400, "%v", err)
		}
	}

	scanned, scannedHeader, err := r.FormFile("scanned")
	if err != nil {
		res = append(res, errors.New(400, "reading file %q failed: %v", "scanned", err))
	} else if err := o.bindScanned(scanned, scannedHeader); err != nil {
		// Required: true
		res = append(res, err)
	} else {
		o.Scanned = &runtime.File{Data: scanned, Header: scannedHeader}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UploadParams) bindScanned(file multipart.File, header *multipart.FileHeader) error {

	return nil
}
