// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UploadHandlerFunc turns a function with the right signature into a upload handler
type UploadHandlerFunc func(UploadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UploadHandlerFunc) Handle(params UploadParams) middleware.Responder {
	return fn(params)
}

// UploadHandler interface for that can handle valid upload params
type UploadHandler interface {
	Handle(UploadParams) middleware.Responder
}

// NewUpload creates a new http.Handler for the upload operation
func NewUpload(ctx *middleware.Context, handler UploadHandler) *Upload {
	return &Upload{Context: ctx, Handler: handler}
}

/*Upload swagger:route POST /uploadscanned upload

Upload a scanned picture

Upload a scanned picture

*/
type Upload struct {
	Context *middleware.Context
	Handler UploadHandler
}

func (o *Upload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUploadParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
