// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Celkopier
Use your friendly RasberryPi to scan your file



    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
